### ISSUE TITLE
编译时发生错误如何解决？

### ISSUE THREAD

**Issue by ntlf9t** [kuoruan/qos-gargoyle#1]
target-x86_64_musl/iproute2-full/iproute2-4.15.0/tc -c qosmon.c -o qosmon.o
qosmon.c:76:1: error: unknown type name 'bool'; did you mean '_Bool'?
 bool use_names = false;
 ^~~~
 _Bool
qosmon.c:76:18: error: 'false' undeclared here (not in a function); did you mean 'raise'?
 bool use_names = false;
                  ^~~~~
                  raise
qosmon.c:79:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char  packet[MAXPACKET];
 ^~~~~~
 __u_char
qosmon.c:126:4: error: unknown type name '__u64'
    __u64      bytes;       //Work bytes last query
    ^~~~~
qosmon.c:127:4: error: unknown type name 'u_char'
    u_char     rtclass;     //True if class is realtime.
    ^~~~~~
qosmon.c:128:4: error: unknown type name 'u_char'
    u_char     backlog;     //Number of packets waiting
    ^~~~~~
qosmon.c:129:4: error: unknown type name 'u_char'
    u_char     actflg;      //True if class is active.
    ^~~~~~
qosmon.c:138:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char classcnt;
 ^~~~~~
 __u_char
qosmon.c:139:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char errorflg;
 ^~~~~~
 __u_char
qosmon.c:140:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char firstflg=1;       //First pass flag
 ^~~~~~
 __u_char
qosmon.c:142:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char DCA;              //Number of download classes active
 ^~~~~~
 __u_char
qosmon.c:143:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char RTDCA;            //Number of realtime download classes active
 ^~~~~~
 __u_char
qosmon.c:144:1: error: unknown type name 'u_char'; did you mean '__u_char'?
 u_char pingon=0;         //Set to one when pinger becomes active.
 ^~~~~~
 __u_char
qosmon.c:166:1: error: unknown type name 'u_short'; did you mean '__u_short'?
 u_short cnt_mismatch=0;
 ^~~~~~~
 __u_short
qosmon.c:167:1: error: unknown type name 'u_short'; did you mean '__u_short'?
 u_short cnt_errorflg=0;
 ^~~~~~~
 __u_short
qosmon.c:168:1: error: unknown type name 'u_short'; did you mean '__u_short'?
 u_short last_errorflg=0;
 ^~~~~~~
 __u_short
qosmon.c:229:14: error: unknown type name 'u_short'; did you mean '__u_short'?
 int in_cksum(u_short *addr, int len)
              ^~~~~~~
              __u_short
qosmon.c: In function 'pinger':
qosmon.c:275:12: error: unknown type name 'u_char'
     static u_char outpack[MAXPACKET];
            ^~~~~~
qosmon.c:279:5: error: unknown type name 'u_char'; did you mean '__u_char'?
     u_char *datap = &outpack[8+sizeof(struct timeval)];
     ^~~~~~
     __u_char
qosmon.c:295:23: warning: implicit declaration of function 'in_cksum' [-Wimplicit-function-declaration]
     icp->icmp_cksum = in_cksum( (u_short *) icp, cc );
                       ^~~~~~~~
qosmon.c:295:34: error: 'u_short' undeclared (first use in this function); did you mean '__u_short'?
     icp->icmp_cksum = in_cksum( (u_short *) icp, cc );
                                  ^~~~~~~
                                  __u_short
qosmon.c:295:34: note: each undeclared identifier is reported only once for each function it appears in
qosmon.c:295:43: error: expected expression before ')' token
     icp->icmp_cksum = in_cksum( (u_short *) icp, cc );
                                           ^
qosmon.c: At top level:
qosmon.c:386:23: warning: 'struct nlmsghdr' declared inside parameter list will not be visible outside of this definition or declaration
                struct nlmsghdr *n, void *arg)
                       ^~~~~~~~
qosmon.c:385:30: warning: 'struct sockaddr_nl' declared inside parameter list will not be visible outside of this definition or declaration
 int print_class(const struct sockaddr_nl *who,
                              ^~~~~~~~~~~
qosmon.c: In function 'print_class':
qosmon.c:388:23: warning: implicit declaration of function 'NLMSG_DATA'; did you mean 'CMSG_DATA'? [-Wimplicit-function-declaration]
     struct tcmsg *t = NLMSG_DATA(n);
                       ^~~~~~~~~~
                       CMSG_DATA
qosmon.c:388:23: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
qosmon.c:389:16: error: dereferencing pointer to incomplete type 'struct nlmsghdr'
     int len = n->nlmsg_len;
                ^~
qosmon.c:390:24: error: 'TCA_MAX' undeclared (first use in this function); did you mean 'TMP_MAX'?
     struct rtattr * tb[TCA_MAX+1];
                        ^~~~~~~
                        TMP_MAX
qosmon.c:392:5: error: unknown type name 'u_char'; did you mean '__u_char'?
     u_char actflg=0;
     ^~~~~~
     __u_char
qosmon.c:396:26: error: 'RTM_NEWTCLASS' undeclared (first use in this function); did you mean 'IPV6_RECVTCLASS'?
     if (n->nlmsg_type != RTM_NEWTCLASS && n->nlmsg_type != RTM_DELTCLASS) {
                          ^~~~~~~~~~~~~
                          IPV6_RECVTCLASS
qosmon.c:396:60: error: 'RTM_DELTCLASS' undeclared (first use in this function); did you mean 'RTM_NEWTCLASS'?
     if (n->nlmsg_type != RTM_NEWTCLASS && n->nlmsg_type != RTM_DELTCLASS) {
                                                            ^~~~~~~~~~~~~
                                                            RTM_NEWTCLASS
qosmon.c:400:12: warning: implicit declaration of function 'NLMSG_LENGTH'; did you mean 'CMSG_LEN'? [-Wimplicit-function-declaration]
     len -= NLMSG_LENGTH(sizeof(*t));
            ^~~~~~~~~~~~
            CMSG_LEN
qosmon.c:400:32: error: dereferencing pointer to incomplete type 'struct tcmsg'
     len -= NLMSG_LENGTH(sizeof(*t));
                                ^~
qosmon.c:407:5: warning: implicit declaration of function 'parse_rtattr' [-Wimplicit-function-declaration]
     parse_rtattr(tb, TCA_MAX, TCA_RTA(t), len);
     ^~~~~~~~~~~~
qosmon.c:407:31: warning: implicit declaration of function 'TCA_RTA' [-Wimplicit-function-declaration]
     parse_rtattr(tb, TCA_MAX, TCA_RTA(t), len);
                               ^~~~~~~
qosmon.c:410:12: error: 'TCA_KIND' undeclared (first use in this function); did you mean 'TCA_MAX'?
     if (tb[TCA_KIND] == NULL) {
            ^~~~~~~~
            TCA_MAX
qosmon.c:418:23: warning: implicit declaration of function 'RTA_DATA'; did you mean 'NO_DATA'? [-Wimplicit-function-declaration]
     if (strcmp((char*)RTA_DATA(tb[TCA_KIND]),"hfsc")) return 0;
                       ^~~~~~~~
                       NO_DATA
qosmon.c:421:26: error: 'TC_H_ROOT' undeclared (first use in this function)
     if (t->tcm_parent == TC_H_ROOT) return 0;
                          ^~~~~~~~~
qosmon.c:450:12: error: 'TCA_STATS2' undeclared (first use in this function); did you mean 'TCA_MAX'?
     if (tb[TCA_STATS2]) {
            ^~~~~~~~~~
            TCA_MAX
qosmon.c:452:25: error: storage size of 'st' isn't known
         struct tc_stats st;
                         ^~
qosmon.c:456:33: error: 'TCA_STATS' undeclared (first use in this function); did you mean 'TCA_STATS2'?
         memcpy(&st, RTA_DATA(tb[TCA_STATS]), MIN(RTA_PAYLOAD(tb[TCA_STATS]), sizeof(st)));
                                 ^~~~~~~~~
                                 TCA_STATS2
In file included from qosmon.c:38:0:
qosmon.c:456:50: warning: implicit declaration of function 'RTA_PAYLOAD'; did you mean 'RTLD_NOLOAD'? [-Wimplicit-function-declaration]
         memcpy(&st, RTA_DATA(tb[TCA_STATS]), MIN(RTA_PAYLOAD(tb[TCA_STATS]), sizeof(st)));
                                                  ^
qosmon.c:465:23: error: 'TCA_STATS_MAX' undeclared (first use in this function); did you mean 'TCA_STATS'?
    struct rtattr *tbs[TCA_STATS_MAX + 1];
                       ^~~~~~~~~~~~~
                       TCA_STATS
qosmon.c:468:4: warning: implicit declaration of function 'parse_rtattr_nested' [-Wimplicit-function-declaration]
    parse_rtattr_nested(tbs, TCA_HFSC_MAX, tb[TCA_OPTIONS]);
    ^~~~~~~~~~~~~~~~~~~
qosmon.c:468:29: error: 'TCA_HFSC_MAX' undeclared (first use in this function); did you mean 'TCA_STATS_MAX'?
    parse_rtattr_nested(tbs, TCA_HFSC_MAX, tb[TCA_OPTIONS]);
                             ^~~~~~~~~~~~
                             TCA_STATS_MAX
qosmon.c:468:46: error: 'TCA_OPTIONS' undeclared (first use in this function); did you mean 'IP_OPTIONS'?
    parse_rtattr_nested(tbs, TCA_HFSC_MAX, tb[TCA_OPTIONS]);
                                              ^~~~~~~~~~~
                                              IP_OPTIONS
qosmon.c:469:12: error: 'TCA_HFSC_RSC' undeclared (first use in this function); did you mean 'TCA_HFSC_MAX'?
    if (tbs[TCA_HFSC_RSC] && (RTA_PAYLOAD(tbs[TCA_HFSC_RSC]) >= sizeof(*sc))) {
            ^~~~~~~~~~~~
            TCA_HFSC_MAX
qosmon.c:469:71: error: dereferencing pointer to incomplete type 'struct tc_service_curve'
    if (tbs[TCA_HFSC_RSC] && (RTA_PAYLOAD(tbs[TCA_HFSC_RSC]) >= sizeof(*sc))) {
                                                                       ^~~
qosmon.c:474:12: error: 'TCA_HFSC_FSC' undeclared (first use in this function); did you mean 'TCA_HFSC_RSC'?
    if (tbs[TCA_HFSC_FSC] && (RTA_PAYLOAD(tbs[TCA_HFSC_FSC]) >= sizeof(*sc))) {
            ^~~~~~~~~~~~
            TCA_HFSC_RSC
qosmon.c: In function 'class_list':
qosmon.c:532:18: error: storage size of 't' isn't known
     struct tcmsg t;
                  ^
qosmon.c:538:5: warning: implicit declaration of function 'll_init_map' [-Wimplicit-function-declaration]
     ll_init_map(&rth);
     ^~~~~~~~~~~
qosmon.c:541:30: warning: implicit declaration of function 'll_name_to_index' [-Wimplicit-function-declaration]
         if ((t.tcm_ifindex = ll_name_to_index(d)) == 0) {
                              ^~~~~~~~~~~~~~~~
qosmon.c:548:9: warning: implicit declaration of function 'rtnl_dump_request' [-Wimplicit-function-declaration]
     if (rtnl_dump_request(&rth, RTM_GETTCLASS, &t, sizeof(t)) < 0) {
         ^~~~~~~~~~~~~~~~~
qosmon.c:548:33: error: 'RTM_GETTCLASS' undeclared (first use in this function)
     if (rtnl_dump_request(&rth, RTM_GETTCLASS, &t, sizeof(t)) < 0) {
                                 ^~~~~~~~~~~~~
qosmon.c:69:28: warning: implicit declaration of function 'rtnl_dump_filter'; did you mean 'dump_filter'? [-Wimplicit-function-declaration]
 #define dump_filter(a,b,c) rtnl_dump_filter(a,b,c,NULL,NULL)
                            ^
qosmon.c:553:9: note: in expansion of macro 'dump_filter'
     if (dump_filter(&rth, print_class, stdout) < 0) {
         ^~~~~~~~~~~
qosmon.c: At top level:
qosmon.c:572:21: error: unknown type name '__u32'; did you mean '__unix'?
 int tc_class_modify(__u32 rate)
                     ^~~~~
                     __unix
qosmon.c: In function 'update_status':
qosmon.c:651:5: error: unknown type name 'u_char'; did you mean '__u_char'?
     u_char i;
     ^~~~~~
     __u_char
qosmon.c: In function 'main':
qosmon.c:795:32: error: 'caddr_t' undeclared (first use in this function); did you mean '__caddr_t'?
             bcopy(hp->h_addr, (caddr_t)&to->sin_addr, hp->h_length);
                                ^~~~~~~
                                __caddr_t
qosmon.c:834:5: warning: implicit declaration of function 'tc_core_init' [-Wimplicit-function-declaration]
     tc_core_init();
     ^~~~~~~~~~~~
qosmon.c:835:9: warning: implicit declaration of function 'rtnl_open'; did you mean 'dlopen'? [-Wimplicit-function-declaration]
     if (rtnl_open(&rth, 0) < 0) {
         ^~~~~~~~~
         dlopen
qosmon.c:946:9: error: unknown type name 'u_char'; did you mean '__u_char'?
         u_char chill;
         ^~~~~~
         __u_char
qosmon.c:1039:25: warning: implicit declaration of function 'tc_class_modify' [-Wimplicit-function-declaration]
                         tc_class_modify(new_dbw_ul);
                         ^~~~~~~~~~~~~~~
qosmon.c: At top level:
qosmon.c:84:20: error: storage size of 'rth' isn't known
 struct rtnl_handle rth;
                    ^~~
Makefile:24: recipe for target 'qosmon.o' failed

**Comment by kuoruan** [comment]
你把编译目录下的 iproute2* 全删了，重新编译看看，我没遇到过你这种错误
