### ISSUE TITLE
请问能否回答一下这个异常？

### ISSUE THREAD

**Issue by 4593645** [kuoruan/qos-gargoyle#2]
首先感谢您能放出石像鬼编译。这边抓的是 Barche :dev 

opwnwrt v17.01.4

src-git GargoylePackages https://github.com/kuoruan/gargoyle-packages.git^97f279b77566224454152ce1d680a831740b8bcc

选上了Gargoyle 内的所有

异常是

`b -znow -zrelro -L /home/pi/git/v17.01.4/staging_dir/target-x86_64_musl-1.1.16/usr/lib make_iptables_rules.c -o make_iptables_rules -lericstools -luci -lm
make_iptables_rules.c: In function 'main':
make_iptables_rules.c:109:5: error: expected ';' before 'fprintf'
     fprintf(stderr, "       -o [TARGET_OPTIONS]\n");
     ^
Makefile:16: recipe for target 'make_iptables_rules' failed
make[4]: *** [make_iptables_rules] Error 1
make[4]: Leaving directory '/home/pi/git/v17.01.4/build_dir/target-x86_64_musl-1.1.16/gargoyle-firewall-util'
Makefile:78: recipe for target '/home/pi/git/v17.01.4/build_dir/target-x86_64_musl-1.1.16/gargoyle-firewall-util/.built' failed
make[3]: *** [/home/pi/git/v17.01.4/build_dir/target-x86_64_musl-1.1.16/gargoyle-firewall-util/.built] Error 2
make[3]: Leaving directory '/home/pi/git/v17.01.4/feeds/GargoylePackages/gargoyle-firewall-util'
package/Makefile:105: recipe for target 'package/feeds/GargoylePackages/gargoyle-firewall-util/compile' failed
make[2]: *** [package/feeds/GargoylePackages/gargoyle-firewall-util/compile] Error 2
make[2]: Leaving directory '/home/pi/git/v17.01.4'
package/Makefile:101: recipe for target '/home/pi/git/v17.01.4/staging_dir/target-x86_64_musl-1.1.16/stamp/.package_compile' failed
make[1]: *** [/home/pi/git/v17.01.4/staging_dir/target-x86_64_musl-1.1.16/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/pi/git/v17.01.4'
/home/pi/git/v17.01.4/include/toplevel.mk:198: recipe for target 'world' failed
make: *** [world] Error 2
`

**Comment by kuoruan** [comment]
只需要编译 qos gargoyle 其他包没调好，也没法用

**Comment by 4593645** [comment]
感谢百忙中回复，具体是？还是说暂时没有办法解决LEDE的编译及其安装？

**Comment by kuoruan** [comment]
其他包是用来移植石像鬼的流量配额功能的，还没有移植完毕
