### ISSUE TITLE
LEDE 17.01.6 编译错误

### ISSUE THREAD

**Issue by baibihuiyi** [kuoruan/qos-gargoyle#3]
iproute2 版本 4.4.0

[ ! -d ./src/ ] || cp -fpR ./src/. /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle

Applying ./patches/001-musl-fixes.patch using plaintext: 
patching file Makefile
patching file qosmon.c
touch /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle/.prepared_b7cd33e9a9bd908eb8eafb21d1ac024768b329da9893e34099c7d8ad5cb9c940
rm -f /home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/stamp/.qos-gargoyle_installed
rm -f /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle/.configured_*
touch /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle/.configured_e587e4cbefa791f8e6d92c6daefd31cf
make -C /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle clean
make[3]: Entering directory '/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle'
rm -rf *.o *~ .*sw* qosmon
make[3]: Leaving directory '/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle'
make -C /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle AR="mipsel-openwrt-linux-musl-gcc-ar" AS="mipsel-openwrt-linux-musl-gcc -c -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -iremap/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=mipsel-openwrt-linux-musl-ld NM="mipsel-openwrt-linux-musl-gcc-nm" CC="mipsel-openwrt-linux-musl-gcc" GCC="mipsel-openwrt-linux-musl-gcc" CXX="mipsel-openwrt-linux-musl-g++" RANLIB="mipsel-openwrt-linux-musl-gcc-ranlib" STRIP=mipsel-openwrt-linux-musl-strip OBJCOPY=mipsel-openwrt-linux-musl-objcopy OBJDUMP=mipsel-openwrt-linux-musl-objdump SIZE=mipsel-openwrt-linux-musl-size CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I /home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/include" LDFLAGS="-L/home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/lib -L/home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/lib -L/home/jun/17.01/staging_dir/toolchain-mipsel_24kc_gcc-6.3.0_musl-1.1.16/usr/lib -L/home/jun/17.01/staging_dir/toolchain-mipsel_24kc_gcc-6.3.0_musl-1.1.16/lib -znow -zrelro -L /home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/lib" BUILD_DIR="/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16" all
make[3]: Entering directory '/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle'
mipsel-openwrt-linux-musl-gcc -D ONLYBG -D_GNU_SOURCE -Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -mips16 -minterlink-mips16 -iremap/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle:qos-gargoyle -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I /home/jun/17.01/staging_dir/target-mipsel_24kc_musl-1.1.16/usr/include -I /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/iproute2-full/iproute2-4.4.0/include -I /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/iproute2-full/iproute2-4.4.0/tc -c qosmon.c -o qosmon.o
qosmon.c: In function 'tc_class_modify':
qosmon.c:67:21: error: too few arguments to function 'rtnl_talk'
 #define talk(a,b,c) rtnl_talk(a,b,c)
                     ^
qosmon.c:636:9: note: in expansion of macro 'talk'
     if (talk(&rth, &req.n, NULL) < 0)
         ^~~~
In file included from /home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/iproute2-full/iproute2-4.4.0/include/utils.h:10:0,
                 from qosmon.c:40:
/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/iproute2-full/iproute2-4.4.0/include/libnetlink.h:73:5: note: declared here
 int rtnl_talk(struct rtnl_handle *rtnl, struct nlmsghdr *n,
     ^~~~~~~~~
Makefile:24: recipe for target 'qosmon.o' failed
make[3]: *** [qosmon.o] Error 1
make[3]: Leaving directory '/home/jun/17.01/build_dir/target-mipsel_24kc_musl-1.1.16/qos-gargoyle'

**Comment by kuoruan** [comment]
估计是由于 iproute 更新了，以前的 patch 不能同了

**Comment by baibihuiyi** [comment]
用你的dev分支版qos-gargoyle 1.0.2 编译通过了
